api:

time:

  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Amsterdam

logger:

ota:

# Secrets in /esphome/common/secrets.yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false
