# Include this file and these three lines in the device's yaml:
# wifi:
#   manual_ip:
#     static_ip: 192.168.xxx.xxx

wifi:
  manual_ip:
    gateway: 192.168.xxx.xxx
    subnet: 255.255.255.0
    dns1: 192.168.xxx.xxx
    dns2: 192.168.xxx.xxx
